/*
 * This source file was generated by the Gradle 'init' task
 */

/*
O custo de um carro novo ao consumidor é a soma do custo de fábrica mais o 
percentual do distribuidor e dos impostos aplicados (primeiro os impostos são 
aplicados sobre o custo de fábrica, e depois o percentual do distribuidor sobre 
o resultado). Supondo que o percentual do distribuidor seja de 28% e os impostos
45%, escreva um algoritmo que leia o custo de fábrica de um carro e informe o 
custo ao consumidor do mesmo;
*/
package com.example.Exercicio12LP;

import java.util.Locale;
import java.util.Scanner;

public class App {
 
    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        double custoFabrica, custoConsumidor;
        double impostos = 0.45;
        double percentualDistribuidor = 0.28;
        
        System.out.print("Informe o custo de fabrica do veículo: ");
        custoFabrica = sc.nextDouble();
        
        custoConsumidor = (custoFabrica * impostos) + custoFabrica;
        custoConsumidor = (custoConsumidor * percentualDistribuidor) + custoConsumidor;
        
        System.out.println(
                "Custo final do veiculo ao consumidor: R$ " +
                String.format("%.2f", custoConsumidor)
        );        
    }
}
