/*
 * This source file was generated by the Gradle 'init' task
 */
/*
16. Escreva um algoritmo que leia o nome e as três notas obtidas por um aluno 
durante o semestre. Calcular a sua média (aritmética), informar o nome e sua 
menção aprovado (media >= 7), Reprovado (media <= 5) e 
Recuperação (media entre 5.1 a 6.9);
*/
package com.example.Exercicio16LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        String nome;
        double nota1, nota2, nota3, media;
        
        System.out.print("Informe o nome do(a) aluno(a): ");
        nome = sc.nextLine();
        System.out.println("Informe as tres notas do(a) aluno(a): ");
        nota1 = sc.nextDouble();
        nota2 = sc.nextDouble();
        nota3 = sc.nextDouble();
        
        media = (nota1 + nota2 + nota3) / 3;
        
        if (media >= 7) {
            System.out.println("\nAluno(a) " + nome + " Aprovado(a)");
        } else if (media >= 5.1 && media <= 6.9) {
            System.out.println("\nAluno(a) " + nome + " Recuperação");
        } else {
            System.out.println("\nAluno(a) " + nome + " Reprovado(a)");
        }
    }
}
