/*
 * This source file was generated by the Gradle 'init' task
 */
/*
22. Faça um algoritmo que receba o preço de custo e o preço de venda de 40 
produtos. Mostre como resultado se houve lucro, prejuízo ou empate para cada 
produto. Informe o valor de custo de cada produto, o valor de venda de cada 
produto, a média de preço de custo e do preço de venda;
*/
package com.example.Exercicio22LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int n;
        
        System.out.print("Informe quantos produtos serão analisados: ");
        n = sc.nextInt();
        
        double precoCusto, precoVenda;
        double mediaVenda = 0;
        double mediaCusto = 0;
        
        for (int i = 0; i < n; i++) {
            System.out.print("Informe o preço de custo do " + 
                    (i+1) + "º produto: ");
            precoCusto = sc.nextDouble();
            System.out.print("Informe o preço de venda do " + 
                    (i+1) + "º produto: ");
            precoVenda = sc.nextDouble();
            
            mediaCusto += precoCusto;
            mediaVenda += precoVenda;
            
            System.out.println("\nPreço de custo do " + 
                    (i+1) + "º produto: R$ " + String.format("%.2f", precoCusto));
            System.out.println("Preço de venda do " + 
                    (i+1) + "º produto: R$ " + String.format("%.2f", precoVenda));
            
            if (precoCusto == precoVenda) {
                System.out.println("Resultado: EMPATE\n");
            } else if (precoCusto < precoVenda) {
                System.out.println("Resultado: LUCRO\n");
            } else {
                System.out.println("Resultado: PREJUIZO\n");
            }
        }
        
        mediaCusto = mediaCusto / n;
        mediaVenda = mediaVenda / n;
        
        System.out.println("Media do preço de custo: R$ " + String.format("%.2f", mediaCusto));
        System.out.println("Media do preço de venda: R$ " + String.format("%.2f", mediaVenda));
        
    }
}
