/*
 * This source file was generated by the Gradle 'init' task
 */
/*
18. Faça um algoritmo que receba a idade de 75 pessoas e mostre mensagem 
informando “maior de idade” e “menor de idade” para cada pessoa. 
Considere a idade a partir de 18 anos como maior de idade;
*/
package com.example.Exercicio18LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int idade;
        
        for (int i = 0; i < 75; i++) {
            System.out.print("Informe a idade da pessoa: ");
            idade = sc.nextInt();
            if (idade >= 18) {
                System.out.println("Maior de idade\n");
            } else {
                System.out.println("Menor de idade\n");
            }
        
        }
    }
}
