/*
 * This source file was generated by the Gradle 'init' task
 */

/*
Elabore um algoritmo que efetue a apresentação do valor da conversão em 
real (R$) de um valor lido em dólar (US$). O algoritmo deverá solicitar o 
valor da cotação do dólar e também aquantidade de dólares disponíveis com o
usuário;
*/
package com.example.Exercicio8LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        double cotacao, dolares, reais;
                
        System.out.print("Informe o valor da cotação do dólar: ");
        cotacao = sc.nextDouble();
        System.out.print("Informe o valor em dólar a ser convertido para reais: ");
        dolares = sc.nextDouble();
        
        reais = dolares * cotacao;
        
        System.out.print(
                "Valor convertido para reais: R$ " + 
                        String.format("%.2f", reais)
        );


    }
}
