/*
 * This source file was generated by the Gradle 'init' task
 */

/*
Faça um algoritmo que receba dois números e exiba o resultado da sua soma;
*/
package com.example.Exercicio1LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        Locale.setDefault(Locale.US);
        
        int numero1, numero2, soma;
        
        System.out.println("Digite dois números para saber a soma: ");
        numero1 = sc.nextInt();
        numero2 = sc.nextInt();
        
        soma = numero1 + numero2;
        
        System.out.println("SOMA = " + soma);   
    }
}
