/*
 * This source file was generated by the Gradle 'init' task
 */

/*
20. A concessionária de veículos “CARANGO VELHO” está vendendo os seus veículos 
com desconto. Faça um algoritmo que calcule e exiba o valor do desconto e o 
valor a ser pago pelo cliente de vários carros. O desconto deverá ser calculado 
de acordo com o ano do veículo. Até 2000 - 12% e acima de 2000 - 7%. O sistema 
deverá perguntar se deseja continuar calculando desconto até que a resposta 
seja: “(N) Não”. Informar total de carros com ano até 2000 e total geral;
*/
package com.example.Exercicio20.logica.programcao;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
       
        int anoCarro = 0;
        double valorCarro = 0.0f;
        double valorComDesconto = 0.0f;
        double valorDesconto = 0.0f;
        int totalCarros = 0;
        int totalCarrosAte2000 = 0;
        char resposta = 'S';
        
        while (resposta != 'N' ) {
            System.out.print("\nInforme o valor do veículo: ");
            valorCarro = sc.nextFloat();
            System.out.print("Informe o ano do veículo: ");
            anoCarro = sc.nextInt();
            
            if (anoCarro > 2000) {
                valorDesconto = valorCarro * 0.07;
                valorComDesconto = valorCarro - valorDesconto;
                totalCarros++;
            } else {
                valorDesconto = valorCarro * 0.12;
                valorComDesconto = valorCarro - valorDesconto;
                totalCarros++;
                totalCarrosAte2000++;
            }
            System.out.println("Valor do desconto: R$ " + String.format("%.2f", valorDesconto) + "\nValor do carro com desconto: " + String.format("%.2f", valorComDesconto));
            System.out.println("\nDeseja continuar? "
                    + "\nSim(S) ou Não(N)");
            resposta = sc.next().charAt(0);
        }
        System.out.println("Total de carros com ano até ano 2000: " + totalCarrosAte2000);
        System.out.println("Total de carros: " + totalCarros);
        
    }
}
