/*
 * This source file was generated by the Gradle 'init' task
 */
 /*
24. Faça um algoritmo que receba “N” números e mostre positivo, negativo 
ou zero para cada número;
 */
package com.example.Exercicio24LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);

        int numero, n;

        System.out.print("Informe quantos números inteiros serão digitados: ");
        n = sc.nextInt();
        
        for (int i = 0; i < n; i++) {
            System.out.print("Informe um número inteiro: ");
            numero = sc.nextInt();

            if (numero == 0) {
                System.out.println("ZERO");
            } else if (numero > 0) {
                System.out.println("POSITIVO");
            } else {
                System.out.println("NEGATIVO");

            }
        }

    }
}
