/*
 * This source file was generated by the Gradle 'init' task
 */
 /*
27. A concessionária de veículos “CARANGO” está vendendo os seus veículos com 
desconto. Faça um algoritmo que calcule e exiba o valor do desconto e o valor 
a ser pago pelo cliente. O desconto deverá ser calculado sobre o valor do 
veículo de acordo com o combustível (álcool – 25%, gasolina – 21% ou diesel
–14%). Com valor do veículo zero encerra entrada de dados. Informe total de 
desconto e total pago pelos clientes;
 */
package com.example.Exercicio27LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);

        double valorVeiculo, valorComDesconto, totalPago, totalDesconto;
        int combustivel;

        totalPago = 0;
        totalDesconto = 0;

        do {
            System.out.print("Informe o valor do veículo: ");
            valorVeiculo = sc.nextDouble();
            if (valorVeiculo == 0)
                    continue;
            System.out.println(
                    "Informe o combustível: "
                    + "\n 1 - álcool"
                    + "\n 2 - gasolina"
                    + "\n 3 - diesel");
            combustivel = sc.nextInt();
            switch (combustivel) {
                case 1:
                    valorComDesconto = valorVeiculo * 0.75;
                    totalPago += valorComDesconto;
                    totalDesconto += (valorVeiculo - valorComDesconto);
                    break;
                case 2:
                    valorComDesconto = valorVeiculo * 0.79;
                    totalPago += valorComDesconto;
                    totalDesconto += (valorVeiculo - valorComDesconto);
                    break;
                case 3:
                    valorComDesconto = valorVeiculo * 0.86;
                    totalPago += valorComDesconto;
                    totalDesconto += (valorVeiculo - valorComDesconto);
                    break;
                default:
                    System.out.println("Valor invávlido");
                    break;
            }
        } while (valorVeiculo != 0);

        System.out.println(
                "Valor total de desconto: R$ "
                + String.format("%.2f", totalDesconto)
                + "\nValor total pago: R$ "
                + String.format("%.2f", totalPago));
    }
}
