/*
 * This source file was generated by the Gradle 'init' task
 */

/*
A Loja Mamão com Açúcar está vendendo seus produtos em 5(cinco)prestações 
sem juros. Faça um algoritmo que receba um valor de uma compra e mostre o 
valor das prestações;
*/
package com.example.Exercicio10LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        double valorCompra, valorPrestacao;
        
        System.out.print("Informe o valor total da compra: ");
        valorCompra = sc.nextDouble();
        
        valorPrestacao = valorCompra / 5;
        
        System.out.println(
                "Valor da compra: R$ " + 
                String.format("%.2f", valorCompra) +
                " a ser paga em 5 prestações cada de : R$ " +
                String.format("%.2f", valorPrestacao)
        );
    }
}
