/*
 * This source file was generated by the Gradle 'init' task
 */

/*
Escreva um algoritmo que leia o nome de um aluno e as notas das três provas 
que ele obteve no semestre. No finalvinformar o nome do aluno e a sua média 
(aritmética);
*/
package com.example.Exercicio5LP;

import java.util.Locale;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);

        String nome;
        double nota1, nota2, nota3, media;
 
        System.out.print("Informe o nome do(a) aluno(a): ");
        nome = sc.nextLine();
        System.out.println("Informe as notas das tres provas:");
        nota1 = sc.nextDouble();
        nota2 = sc.nextDouble();
        nota3 = sc.nextDouble();
        
        media = (nota1 + nota2 + nota3) / 3;
        
        System.out.println("Nome aluno(a): " + nome +
                " - Média: " + String.format("%.1f", media));
    }
}
