/*
 * This source file was generated by the Gradle 'init' task
 */
/*
17. Leia 80 números e ao final informar quantos número(s) est(á)ão no intervalo
entre 10 (inclusive) e 150 (inclusive);
*/
package com.example.Exercicio17LP;

import java.util.Locale;
import java.util.Scanner;

public class App {


    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int contagem, numero;
        
        contagem = 0;
        for (int i = 0; i < 80; i++) {
            System.out.print("\nInforme um numero inteiro: ");
            numero = sc.nextInt();
            if (numero >= 10 && numero <= 150) {
                contagem++;
            }
        }
        System.out.println("Quantidade de numeros dentro do intervalo: " + contagem);
    }
}
