/*
 * This source file was generated by the Gradle 'init' task
 */
/*
21. Escreva um algoritmo que leia os dados de “N” pessoas (nome, sexo, idade e 
saúde) e informe se está apta ou não para cumprir o serviço militar obrigatório.
Informe os totais;
*/
package com.example.Exercicio21LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int apto = 0;
        int naoApto = 0;
        String nome;
        char genero;
        int idade, saude;
        int candidatos;
        
        System.out.print("Informe quantas pessoas serão avaliadas: ");
        candidatos = sc.nextInt();
        
        for (int i = 0; i < candidatos; i++) {
            System.out.print("Informe nome da " + (i+1) + "a pessoa: ");
            sc.nextLine();
            nome = sc.nextLine();
            System.out.print("Informe o genero (M/F): ");
            genero = sc.next().charAt(0);
            System.out.print("Informe a idade: ");
            idade = sc.nextInt();
            System.out.print("Estado de saúde boa: (1 - SIM / 2 - NAO): ");
            saude = sc.nextInt();

            if (saude == 2 || idade < 18 || idade > 45) {
                naoApto++;
                continue;
            }
            apto++;
        }
        
        System.out.println(
                "\nTotal de pessoas aptas: " + apto +
                "\nTotal de pessoas NAO aptas: " + naoApto
        );

        
    }
}
