/*
 * This source file was generated by the Gradle 'init' task
 */
/*
Leia dois valores para as variáveis A e B, e efetuar as trocas dos valores de 
forma que a variável A passe a possuir ovalor da variável B e a variável B passe 
a possuir o valor da variável A. Apresentar os valores trocados;
*/

package com.example.Exercicio6LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);

        int numero1, numero2;
        
        System.out.println("Digite dois valores inteiros: ");
        numero1 = sc.nextInt();
        numero2 = sc.nextInt();
        System.out.println(
                "Valor na variavel 'A': " + numero1 +
                "\nValor na variavel 'B': " + numero2
        );
        
        numero1 = numero1 + numero2;
        numero2 = numero1 - numero2;
        numero1 = numero1 - numero2;
        
        System.out.println(
                "Valor na variavel 'A' apos a troca: " + numero1 +
                "\nValor na variavel 'B'  apos a troca: " + numero2
        );
    }
}
