/*
 * This source file was generated by the Gradle 'init' task
 */

/*
Faça um algoritmo que receba dois números e ao final mostre a soma, subtração, 
multiplicação e a divisão dos dois números lidos;
*/
package com.example.Ecercicio2LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        double numero1, numero2, soma, subtracao, multiplicacao, divisao;
        
        System.out.println("Digite dois números para saber a soma, subtração, "
                + "multiplicação e a divisão entre eles: ");
        numero1 = sc.nextDouble();
        numero2 = sc.nextDouble();
        
        soma = numero1 + numero2;
        subtracao = numero1 - numero2;
        multiplicacao = numero1 * numero2;
        divisao = numero1 / numero2;
        
        System.out.println(
                "SOMA = " + soma + 
                "\nSUBTRAÇAO = " + subtracao + 
                "\nMULTIPLICACAO = " + multiplicacao + 
                "\nDIVISAO = " + divisao);
    }
}
