/*
 * This source file was generated by the Gradle 'init' task
 */

/*
Leia uma temperatura em graus Celsius e apresentá-la convertida em graus 
Fahrenheit. Afórmula de conversão é:F=(9*C+160) / 5, sendo F a temperatura 
em Fahrenheit e C a temperatura emCelsius;
*/
package com.example.Exercicio7LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        double celsius, fahrenheit;

        System.out.print("Informe a temperatura em graus Celsius: ");
        celsius = sc.nextDouble();
        
        fahrenheit = ((9 * celsius) + 160) / 5;
        
        System.out.println(
                "A temperatura em graus Fahrenheit é : " + 
                        String.format("%.0f", fahrenheit));
        
    }
}
