/*
 * This source file was generated by the Gradle 'init' task
 */

/*
13. Faça um algoritmo que receba um número e mostre uma mensagem caso este 
número seja maior que 10;
*/
package com.example.Exercicio13LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int numero;
            
        System.out.print("Informe um numero inteiro: ");
        numero = sc.nextInt();
        
        if (numero > 10) {
            System.out.println("\nNumero maior que 10");
        }
    }
}
