/*
 * This source file was generated by the Gradle 'init' task
 */
 /*
26. Faça um algoritmo que leia um número de 1 a 5 e escreva por extenso. Caso o
usuário digite um número que não esteja neste intervalo, exibir a seguinte 
mensagem: número inválido;
 */
package com.example.Ecercicio26LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);

        int numero;

        System.out.print("Informe um número inteiro de 1 a 5: ");
        numero = sc.nextInt();

        switch (numero) {
            case 1:
                System.out.println("UM");
                break;
            case 2:
                System.out.println("DOIS");
                break;
            case 3:
                System.out.println("TRES");
                break;
            case 4:
                System.out.println("QUATRO");
                break;
            case 5:
                System.out.println("CINCO");
                break;
            default:
                System.out.println("Número inválido!!!");
                break;
        }
    }
}
