/*
 * This source file was generated by the Gradle 'init' task
 */
/*
15. Faça um algoritmo que receba um número e diga se este número está no 
intervalo entre 100 e 200;
*/
package com.example.Exercicio15LP;

import java.util.Locale;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Locale.setDefault(Locale.US);
        Scanner sc = new Scanner(System.in);
        
        int numero;
        
        System.out.print("Informe um numero inteiro: ");
        numero = sc.nextInt();
        
        if (numero >= 100 && numero <= 200) {
            System.out.println("Numero informado está dentro do intervalo.");
        } else {
            System.out.println("Numero informado não está dentro do intervalo.");
        }
    }
}
